### ISSUE TITLE
Notification: wrong color for content

### ISSUE THREAD

**Issue by leape** [db-ui/design#1]
### Which libraries are impacted?

- [ ] Figma Core Foundations
- [ ] Figma Core Components
- [ ] Figma Core Patterns
- [ ] Figma Core Icons
- [X] Sketch Core (Foundations/Components/Patterns)
- [ ] Sketch Core Icons

### Which version is impacted?

3.0.0-Beta-1

### Reproduction case

01--Regular/Feedback/Notification (Beta)/(Def) Inline Docked/(Def) Adaptive/(Def) Closeable/Icon - Text/Headline - Text - Link Bottom

Headline, text and link uses hex value instead of color variable

### Expected Behaviour

Headline, text and link should use on color variable

### Screenshots

![image](https://github.com/db-ui/design-feedback/assets/6907841/ca0f8ebf-6b84-4ff0-a0f6-7c60c27fdb63)

**Comment by LSchroff** [comment]
Wird im aktuellen Sprint bearbeitet
