### ISSUE TITLE
Accordion Variante Card: Beim Ausgeklappen des AccordionItems ist vertikal nicht genug Platz

### ISSUE THREAD

**Issue by hannastephaniahahn** [db-ui/design#113]
### Which design system content is impacted? * (PLEASE SELECT THE LIBRARY)

- [ ] Figma Core Foundations
- [X] Figma Core Components
- [ ] Figma Core Patterns
- [ ] Figma Core Icons
- [ ] Sketch Core (Foundations/Components/Patterns)
- [ ] Sketch Core Icons

### Which version is impacted?

0.3.2

### Reproduction case

Komponente: Accordion
Variante: Card
Adaptive Size: Desktop-Functional

Umstellen des ersten AccordionItems auf Open wird in der Komponente nicht genug Platz geschafft.

Fix maybe (?): Slot im AccorionItem Höhe default auf "Hug contents" einstellen?

### Expected

Cardplatz passt sich den dargellten Inhalten an.

### Screenshots

<img width="559" alt="image" src="https://github.com/user-attachments/assets/feb4b872-1e0f-449d-bdfc-31dbc2c6103b">
![image](https://github.com/user-attachments/assets/0b173b9e-f868-4f76-be2f-5cfedd88cec5)

**Comment by MeDoingUX** [comment]
Tatsächlich ist es nur beim ersten Accordion Item so, dass die Umschaltung auf "Accordion Item Open" den Header zusammenfallen lässt. 
![image](https://github.com/user-attachments/assets/160b6e09-a706-458e-8f50-24fbfbbddfa3)
Initial ist der Resizing-Modus richtig gewählt (Hug), geht aber beim Umschalten verloren (Fill).
![image](https://github.com/user-attachments/assets/f640883c-8cc9-403b-8705-75f88a5f2503)
Wenn man das gleiche beim zweiten Item macht bleibt der Resizing-Modus erhalten (Hug), alles OK.
Vmtl. ein Bug in Figma und nicht in der Library?

**Comment by leape** [comment]
@hannastephaniahahn Ja ist leider ein Figma Bug. Wir weisen da auch in den [Specs](https://www.figma.com/design/mlJ6R0GkfR15a93KSlqXtB/DB-UX-DS-v3---Core-Components-(Beta)---v0.4.0?node-id=3588-3926&node-type=FRAME&t=PVtMJNtSdo0hjAOb-11) drauf hin und zeigen – wie es @MeDoingUX auch schon aufgezeigt hat – wie man den Bug manuell fixen kann.
