### ISSUE TITLE
Header Properties lassen sich nur bei Full-Width bearbeiten

### ISSUE THREAD

**Issue by leape** [db-ui/design#55]
### Which design system content is impacted?

- [ ] Figma Core Foundations
- [X] Figma Core Components
- [ ] Figma Core Patterns
- [ ] Figma Core Icons
- [ ] Sketch Core (Foundations/Components/Patterns)
- [ ] Sketch Core Icons

### Which version is impacted?

3.0.0-Beta-1

### Reproduction case

Ich kann den Header nur bei "full width" rechts. Die Optionen verschwinden, wenn ich eine andere Größe auswähle.

### Expected

Der Header sollte auch in den anderen Größen konfigurierbar sein.

### Screenshots

![image](https://github.com/db-ui/design/assets/6907841/746937ac-101d-44d1-b0bc-f4284d6f8a5f)

**Comment by LSchroff** [comment]
Wird als Ticket mit aufgenommen und in einem der kommenden Sprints bearbeitet.
