### ISSUE TITLE
Tag: Leading Icon Farbe

### ISSUE THREAD

**Issue by leape** [db-ui/design#59]
### Which design system content is impacted?

- [ ] Figma Core Foundations
- [X] Figma Core Components
- [ ] Figma Core Patterns
- [ ] Figma Core Icons
- [ ] Sketch Core (Foundations/Components/Patterns)
- [ ] Sketch Core Icons

### Which version is impacted?

3.0.0-Beta-1

### Reproduction case

Das Leading-Icon hat die falsche Farbe (alle Varianten)

### Expected

Das Leading Icon sollte wie der Text auch die richtige Farbe haben

### Screenshots

![image](https://github.com/db-ui/design/assets/6907841/65848ec0-f599-464f-b1e7-99c82b9f40cc)

**Comment by LSchroff** [comment]
Wird im aktuellen Sprint bearbeitet.

**Comment by leape** [comment]
Fehler kann nicht mehr reproduziert werden.
