### ISSUE TITLE
Component Tags in Figma ergänzen

### ISSUE THREAD

**Issue by leape** [db-ui/design#63]
### The problem

Die Komponenten werden z.T. nicht gut gefunden

### The solution

Über eine aussagekräftige Beschreibung der Komponenten inkl. Tags kann die Auffindbarkeit verbessert werden.

### Examples

![image](https://github.com/db-ui/design/assets/6907841/8cc932a9-bd6c-48c3-aecb-5821445ad4ff)

**Comment by LSchroff** [comment]
Wird als Ticket in den Backlog aufgenommen und in einem der nächsten Sprints bearbeitet.
