### ISSUE TITLE
Card Spacing nicht logisch

### ISSUE THREAD

**Issue by leape** [db-ui/design#68]
### Which design system content is impacted?

- [ ] Figma Core Foundations
- [ ] Figma Core Components
- [ ] Figma Core Patterns
- [ ] Figma Core Icons
- [ ] Sketch Core (Foundations/Components/Patterns)
- [ ] Sketch Core Icons

### Which version is impacted?

3.0.0-Beta-1

### Reproduction case

Das Spacing in der Card stimmt nicht mit dem Spacing der Card-Properties überein.

### Expected

Card Spacing soll mit dem eingesetzten Spacing übereinstimmen.
md = md
lg = lg
sm = sm

### Screenshots

![image](https://github.com/db-ui/design/assets/6907841/2511ef91-8e1b-416f-a361-eeb969de8b4c)

**Comment by LSchroff** [comment]
Wird als Ticket mit aufgenommen und in einem der kommenden Sprints bearbeitet.

**Comment by leape** [comment]
+ Ergänzen von "none"
