### ISSUE TITLE
Card Lvl1 + 2 haben falschen Radius

### ISSUE THREAD

**Issue by leape** [db-ui/design#74]
### Which design system content is impacted?

- [ ] Figma Core Foundations
- [X] Figma Core Components
- [ ] Figma Core Patterns
- [ ] Figma Core Icons
- [ ] Sketch Core (Foundations/Components/Patterns)
- [ ] Sketch Core Icons

### Which version is impacted?

3.0.0-Beta-1

### Reproduction case

Level 1 und Level 2 haben Radius von 8px = db-border-radius-sm

### Expected

Level 1 und Level 2 sollten einen Radius von 4px = db-border-radius-xs haben

### Screenshots

![image](https://github.com/db-ui/design/assets/6907841/58840d8e-6195-4bad-8e5c-29992611d5b7)

**Comment by LSchroff** [comment]
Wird als Ticket mit aufgenommen und in einem der kommenden Sprints bearbeitet.
