### ISSUE TITLE
Missing Icon

### ISSUE THREAD

**Issue by estherux** [db-ui/design#90]
### The problem

[
<img width="384" alt="Fehlendes Icon" src="https://github.com/user-attachments/assets/21b8af76-97a6-4966-b75c-9dc87d222f0b">
](url)

"Priority"-Icon fehlt in der Icon 3er Library für Figma. Ist ein Standard Icon, was bekannt ist für "MER ohne Rollstuhl". Benötigen wir für die Darstellung im Wagenlayout. 

### The solution

Aufnahme des Priority Icons in die Figma PV Icon Library.

**Comment by leape** [comment]
@estherux Das Priority Icon wurde in Absprache mit FV und S.R überarbeitet und jetzt als "Traveler with Reduced Mobility" in der Library vorhanden.

**Comment by estherux** [comment]
Ok, ich habe das Icon internen Mitarbeitern gezeigt und die Resonanz war nicht so gut und sie haben gefragt, ob das Icon vertestet worden ist?
