### ISSUE TITLE
Fehler in Icon-Library - Icon verdreht

### ISSUE THREAD

**Issue by YaHoUx** [db-ui/design#94]
In der DB UI Mono Library liegt das Icon **sort_up** verkehrt herum vor. Wird es von den Entwicklern benutzt, findet man es auch verkehrt herum in der Anwendung wieder.

Sketch
![94118f19-b45a-4e5f-b5bf-eb2b76391f76](https://github.com/user-attachments/assets/4708b6a4-ff2f-4466-ba94-ec7092ccc6c5)

Mono
![Bildschirmfoto 2024-08-07 um 14 25 26](https://github.com/user-attachments/assets/3b152d18-141f-437f-a170-008c5815e62d)

**Comment by LSchroff** [comment]
Wird im nächsten Sprint bearbeitet.
